# Generated by Django 3.2.8 on 2022-06-24 22:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='numbersregisters',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='numbersregisters',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='numbersregisters',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
