# Generated by Django 3.2.8 on 2022-06-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220624_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numbersregisters',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='numbersregisters',
            name='function_first',
        ),
        migrations.RemoveField(
            model_name='numbersregisters',
            name='function_second',
        ),
        migrations.RemoveField(
            model_name='numbersregisters',
            name='function_third',
        ),
        migrations.AddField(
            model_name='numbersregisters',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='numbersregisters',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='phone'),
        ),
    ]
