name: Django CI
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version:
          - 3.9
    steps:
      - uses: actions/checkout@v3
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v3
        with:
          python-version: '${{ matrix.python-version }}'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Docker Compose
        run: docker-compose up --build -d
      - name: Build Docker image
        run: docker build -f PROJETO-INTEGRADOR .
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Heroku container registry
        env:
          HEROKU_API_KEY: '${{secrets.HEROKU_API_KEY}}'
        run: 'heroku container:login'
      - name: Build and Push
        env:
          HEROKU_API_KEY:
            '[object Object]': null
        run: 'heroku container:push -a ${{secrets.HEROKU_APP_NAME}}web'
      - name: release
        env:
          HEROKU_API_KEY:
            '[object Object]': null
        run: 'heroku container:release -a ${{secrets.HEROKU_APP_NAME}} web'
