name: Deploy HEROKU

on:
  push:
    branches: [master]

jobs:
  build:
    name: Setup 
    runs-on: ubuntu-latest
    environment: pi-prod-gcp
    #env:
      #IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/app:latest
    steps:
      # Git checkout
      - name: Checkout
        uses: actions/checkout@v2
        
      # instala dependências
      - name: Install Dependencies
        run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
                
        
       #comppose 
      - name: Docker Compose
        run:  docker-compose up --build -d
     # - name: Teste
      #  run: ./django_pi_v2 python manage.py test 
      
        # build image
      - name: Build Docker image
        run: docker build .

   
      # push image to registry
     # - name: Push Docker image
    #    run: docker push af4e136f6c19
  
  deploy: 
    needs: build
    runs-on: ubuntu-latest
    environment: pi-prod-gcp
    steps:
      - uses: actions/checkout@v2
      - name: Login to Heroku container registry      
        env:
         HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: heroku container:login
      - name: Build and Push
        env:
         HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: heroku container:push web --app registry.heroku.com/pi-v3
        #web registry.heroku.com/pi-v3
        
      - name: release 
        env:
         HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: heroku container:release web --app registry.heroku.com/pi-v3
        #heroku container:release  web --app application-name

      #  docker push registry.heroku.com/appname/web
#heroku container:release web -a appname



