name: Deploy GCP

on:
  push:
    branches: [master]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
       APP_ID: app
       RUN_REGION: us-central1 
       SA_KEY_JSON: ${{ secrets.GCP_CREDENTIALS }}

jobs:
  deploy:
    name: Deploy to cloud run
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'to deploy')"
    steps:
      - uses: actions/checkout@v2
        # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}


      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/app:latest
    steps:
      # Git checkout
      - name: Checkout        

      # Login to GCP
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # gcloud configure docker
      - name: Configure Docker
        run: gcloud auth configure-docker --quiet
        
      # instala dependências
      - name: Install Dependencies
        run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
                
        
       #comppose 
      - name: Docker Compose
        run:  docker-compose up --build -d
        # build image
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      # push image to registry
      - name: Push Docker image
        run: docker push $IMAGE_NAME

        # Build and push image to Google Container Registry
      #- name: Build
       # run: gcloud builds submit --tag gcr.io/$PROJECT_ID/$APP_ID:$GITHUB_SHA

      # deploy image
      - name: Deploy Docker image
        run: gcloud run deploy $APP_ID --image gcr.io/$PROJECT_ID/$APP_ID:$GITHUB_SHA --platform managed --region us-central1 --memory 128Mi --min-instances 0 --max-instances 1 --port $PORT --allow-unauthenticated
